name: Build
on:
  push:
    branches:
      - master
      - feature/upgrade_github_action_config #todo: test
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout our repository under $GITHUB_WORKSPACE so the workflow can access it.
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # define the java version to 11.
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11

      # Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # This action allows caching dependencies and build outputs to improve workflow execution time.
      - name: Cache multiple paths
        uses: actions/cache@v3
        with:
          path: |
            ~/cache
            !~/cache/exclude
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      # run all unit tests
      - name: Run Tests
        run: ./gradlew test

      # build the project
      - name: Build Project
        run: ./gradlew assembleDebug

      - name: 🤖 Upload apk
        uses: actions/upload-artifact@v2
        with:
          name: debug apk
          path: app/build/outputs/apk/debug/app-debug.apk